### ISSUE TITLE
随笔

### ISSUE THREAD

**Issue by baymaxxjf** [baymaxxjf/blog_essays#34]
在/etc/netplan 的唯一一个配置文件配置如下
``` yaml
network:
    ethernets:
        [网卡名称]:
            dhcp4: false
            addresses: [ip/24]
            gateway4: 192.168.43.1
            nameservers:
                    addresses: [192.168.43.1,114.114.114.114]
           #renderer: NetworkManager  此处务必注释
```
``` sh
// 应用更改
sudo netplan apply
```
执行上述命令后，`ip addr`查看 [网卡名称]有一条ip信息
重启后或者重连wifi后，`ip addr`查看 [网卡名称]有两条ip信息，多了一条动态分配的ip信息
如果此处ip填写的是已分配的ip或者不合法的ip,则按照动态分配ip联网，但无论是否重启都无法用填写的ip和动态分配的ip连上ssh
填写还未分配的ip则没事，重启后可以采用动态分配的ip和填写的ip连上ssh，未重启因为会被重置成一条ip信息，因此也只能用上面配置填的ip连ssh
